stages:
-   test

variables:
    DOCKER_PUBLISH_HOST: docker
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    NO_PROXY: docker,$LOCAL_REGISTRY
    no_proxy: docker,$LOCAL_REGISTRY
    https_proxy: $http_proxy
    OS_CLOUD: default

.test: &test
    stage: test
    services:
    -   name: docker:dind
    script:
    -   echo 'Acquire::http::Proxy "'$http_proxy'";' > /etc/apt/apt.conf.d/99proxy
    -   cat /etc/apt/apt.conf.d/99proxy
    -   apt-get update && apt-get install -y gcc iproute2
    -   pip install -r requirements-test.txt
    -   gw="$(getent -i hosts docker|cut -d ' ' -f 1)"
    -   dest="$(python tests/find_route_dest.py)"
    -   ip route add $dest via $gw
    -   echo ip route add $dest via $gw
    -   pip install .
    -   flake8 openstack_notifier tests
    -   which mypy && mypy --strict openstack_notifier || true
    -   python -m pytest --log-level debug --cov openstack_notifier tests/

py37:
  <<: [*test]
  image: python:3.7-slim

py36:
  <<: [*test]
  image: python:3.6-slim
